export const AVAILABLE_TABLES = [
	'categories',
	'customers',
	'employee_territories',
	'employees',
	'order_details',
	'orders',
	'products',
	'regions',
	'shippers',
	'suppliers',
	'territories',
];

export const TABLE_FIELDS = {
	categories: ['*', 'categoryID', 'categoryName', 'description', 'picture'],
	customers: [
		'*',
		'customerID',
		'companyName',
		'contactName',
		'contactTitle',
		'address',
		'city',
		'region',
		'postalCode',
		'country',
		'phone',
		'fax',
	],
	employee_territories: ['*', 'employeeID', 'territoryID'],
	employees: [
		'*',
		'employeeID',
		'lastName',
		'firstName',
		'title',
		'titleOfCourtesy',
		'birthDate',
		'hireDate',
		'address',
		'city',
		'region',
		'postalCode',
		'country',
		'homePhone',
		'extension',
		'photo',
		'notes',
		'reportsTo',
		'photoPath',
	],
	order_details: ['*', 'orderID', 'productID', 'unitPrice', 'quantity', 'discount'],
	orders: [
		'*',
		'orderID',
		'customerID',
		'employeeID',
		'orderDate',
		'requiredDate',
		'shippedDate',
		'shipVia',
		'freight',
		'shipName',
		'shipAddress',
		'shipCity',
		'shipRegion',
		'shipPostalCode',
		'shipCountry',
	],
	products: [
		'*',
		'productID',
		'productName',
		'supplierID',
		'categoryID',
		'quantityPerUnit',
		'unitPrice',
		'unitsInStock',
		'unitsOnOrder',
		'reorderLevel',
		'discontinued',
	],
	regions: ['*', 'regionID', 'regionDescription'],
	shippers: ['*', 'shipperID', 'companyName', 'phone'],
	suppliers: [
		'*',
		'supplierID',
		'companyName',
		'contactName',
		'contactTitle',
		'address',
		'city',
		'region',
		'postalCode',
		'country',
		'phone',
		'fax',
		'homePage',
	],
	territories: ['*', 'territoryID', 'territoryDescription', 'regionID'],
};
